# Generated by Django 3.2.3 on 2021-05-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='designation',
            field=models.CharField(choices=[(1, 'Member'), (2, 'Convenor'), (3, 'Admin')], default='Member', max_length=100),
        ),
    ]
