# Generated by Django 3.2.3 on 2021-05-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_info_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='designation',
            field=models.CharField(choices=[('1', 'Member'), ('2', 'Convenor'), ('3', 'Admin')], default='1', max_length=100),
        ),
    ]
