# Generated by Django 3.2.3 on 2021-05-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_info_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='designation',
            field=models.CharField(choices=[('Member', 'Member'), ('Convenor', 'Convenor'), ('Admin', 'Admin')], default='Member', max_length=100),
        ),
    ]
