# Generated by Django 3.2.3 on 2021-05-26 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_request_club'),
        ('accounts', '0004_alter_info_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='club',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='base.club'),
        ),
    ]
