# Generated by Django 3.2.3 on 2021-05-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_info_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='club',
        ),
    ]
