# Generated by Django 4.0.4 on 2022-05-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_info_id_alter_permission_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission_assignment',
            old_name='club_id',
            new_name='club',
        ),
        migrations.RenameField(
            model_name='permission_assignment',
            old_name='user_id',
            new_name='user',
        ),
    ]
