# Generated by Django 3.2.3 on 2021-05-18 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_club_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='user',
        ),
        migrations.AddField(
            model_name='club',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
