# Generated by Django 3.2.3 on 2021-05-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210518_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='user',
            new_name='users',
        ),
    ]
