# Generated by Django 3.2.3 on 2021-05-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_info_item_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
