# Generated by Django 3.2.3 on 2021-05-21 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.club'),
        ),
    ]
